version: '3.4'

services:
  main:
    image: unogameserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
  
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: Senderion
      POSTGRES_DB: Users
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
